# Generated by Django 5.0.6 on 2026-05-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Manually approved by Admin after KYC review'),
        ),
        migrations.AddField(
            model_name='shop',
            name='pan_vat_number',
            field=models.CharField(blank=True, help_text='PAN/VAT/Registration Number', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('physical', 'Physical Store'), ('online', 'Online Store')], default='physical', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.CreateModel(
            name='ShopKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID Card'), ('citizenship', 'Citizenship Certificate'), ('driving_license', 'Driving License')], max_length=20)),
                ('document_front', models.ImageField(upload_to='kyc_documents/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc_documents/')),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('permanent_address', models.TextField(blank=True)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='shops.shop')),
            ],
        ),
    ]
