# Generated by Django 5.0.6 on 2026-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_latitude_alter_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='business_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('pharmacy', 'Pharmacy'), ('furniture', 'Furniture'), ('restaurant', 'Restaurant'), ('cosmetics', 'Cosmetics'), ('agriculture', 'Agriculture'), ('stationery', 'Stationery'), ('mobile', 'Mobile Shop')], default='grocery', max_length=20),
        ),
    ]
