# Generated by Django 5.0.6 on 2026-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shoprole_shopsettings_shopsubaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight as a top featured shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Highlight as a paid sponsored shop'),
        ),
    ]
