# Generated by Django 5.0.14 on 2026-05-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shop_average_rating_shop_rating_count_shop_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='shop_banners/'),
        ),
    ]
