# Generated by Django 5.0.14 on 2026-05-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_shop_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
