# Generated by Django 5.0.6 on 2026-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_message_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='merchant_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='shop_qrs/'),
        ),
    ]
