# Generated by Django 5.0.6 on 2026-05-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_shop_merchant_code_shop_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='promotion_label',
            field=models.CharField(blank=True, choices=[('', 'None'), ('sale', 'Sale'), ('offer', 'Special Offer'), ('new', 'New Arrival'), ('hot', 'Hot Deal'), ('featured', 'Featured')], default='', max_length=20),
        ),
    ]
