# Generated by Django 5.0.6 on 2026-05-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_shop_promotion_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='promotion_label',
            field=models.CharField(blank=True, default='', help_text='Custom promotion text (e.g., Sale, Special Offer, or any custom text)', max_length=20),
        ),
    ]
