# Generated by Django 5.0.6 on 2026-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_subscriptionplan_shopsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_approval_required', models.BooleanField(default=True)),
                ('product_approval_required', models.BooleanField(default=True)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('minimum_payout_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('enable_chat', models.BooleanField(default=True)),
                ('enable_reviews', models.BooleanField(default=True)),
                ('enable_cod', models.BooleanField(default=True)),
                ('marketplace_name', models.CharField(default='Sajilo Dokan', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
