# Generated by Django 5.0.6 on 2026-06-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_min_order_quantity_product_wholesale_price'),
        ('shops', '0019_commissionrate_payoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_type', models.CharField(choices=[('metro', 'Metropolitan City'), ('sub_metro', 'Sub-Metropolitan City'), ('municipality', 'Municipality'), ('rural_municipality', 'Rural Municipality / Village')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'verbose_name_plural': 'Shop Categories'},
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.shopcategory'),
        ),
        migrations.AddField(
            model_name='shop',
            name='verification_tier',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('personal_verified', 'Identity Verified'), ('business_verified', 'Business Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shops.shopcategory'),
        ),
        migrations.AddField(
            model_name='shopkyc',
            name='business_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='shopkyc',
            name='kyc_type',
            field=models.CharField(choices=[('personal', 'Personal ID Verification'), ('business', 'Business Registration Verification')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='shopkyc',
            name='pan_vat_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shops.district'),
        ),
        migrations.AddField(
            model_name='shop',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.district'),
        ),
        migrations.CreateModel(
            name='MarketHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='market_banners/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_hubs', to='shops.city')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='market_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.markethub'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='shops.province'),
        ),
        migrations.AddField(
            model_name='shop',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.province'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='shops.city')),
            ],
        ),
        migrations.AddField(
            model_name='markethub',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_hubs', to='shops.street'),
        ),
        migrations.AddField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.street'),
        ),
        migrations.AddField(
            model_name='shop',
            name='trade_types',
            field=models.ManyToManyField(blank=True, related_name='shops', to='shops.tradetype'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='shops.city')),
            ],
            options={
                'unique_together': {('city', 'number')},
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.ward'),
        ),
        migrations.CreateModel(
            name='ShopCategoryPermittedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitted_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_shops', to='products.productcategory')),
                ('shop_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_products', to='shops.shopcategory')),
            ],
            options={
                'unique_together': {('shop_category', 'permitted_product_category')},
            },
        ),
    ]
