# Generated by Django 5.0.6 on 2026-06-13 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_city_district_province_tradetype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shop_lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_featured', 'created_at'], name='shop_featured_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_sponsored', 'created_at'], name='shop_sponsored_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['created_at'], name='shop_created_idx'),
        ),
    ]
