# Generated by Django 5.0.6 on 2026-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttag_rename_base_price_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight as a top featured product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Highlight as a paid sponsored product'),
        ),
    ]
