# Generated by Django 5.0.6 on 2026-05-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_featured_product_is_sponsored'),
        ('shops', '0006_shop_is_featured_shop_is_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_subcategories', to='shops.shop'),
        ),
        migrations.CreateModel(
            name='ProductChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_child_categories', to='shops.shop')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='products.productsubcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Child Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productchildcategory'),
        ),
    ]
