# Generated by Django 5.0.6 on 2026-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_min_order_quantity_product_wholesale_price'),
        ('shops', '0021_shop_shop_lat_lng_idx_shop_shop_featured_created_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['moderation_status', 'created_at'], name='prod_mod_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['selling_price'], name='prod_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_sponsored', 'created_at'], name='prod_featured_spons_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='prod_created_idx'),
        ),
    ]
